# YAML Lint configuration for GitHub Actions workflows
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Comments
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

  # Document start
  document-start:
    present: false

  # Key ordering
  key-ordering: disable

# Ignore paths
ignore: |
  node_modules/
  .git/
  vendor/