---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  document-start:
    present: true
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
  indentation:
    spaces: 2
    indent-sequences: true
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1